<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Indicator;

class IndicatorSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            'GKG',
            'Pipilan Kering Panen',
            'Umbi Segar/Umbi kering panen',
            'Umbi Segar',
            'Biji Kering',
            'Daun Segar',
            'Buah Segar',
            'Bunga Segar',
            'Bunga Basah',
            'Pohon',
            'Tebu Giling',
            'Kapas Berbiji',
            'Daun Kering',
            'Buah Kering',
            'Buah',
            'Serat Basah',
            'Rimpang Kering',
            'Lateks',
            'Tandan buah segar',
            'Buah Kelapa',
            'Bunga Kering',
            'Mentor Basah',
            'Kulit Basah',
            'Polong Basah',
            'Buah Basah',
            'Gula Merah',
            'Nira',
            'Daun Basah',
            'Kulit Kering',
            'Biji Basah',
            'Biji',
            'Serat Kering',
            'Hewan Hidup',
            'Telur',
            'Susu',
            'Ikan Segar',
            'Kayu Gelondongan',
            'Ikan Hidup',
            'Galian Pasir',
            'Tahu',
            'Jenang',
            'Rokok',
            'Baju Anak-Anak',
            'Jaket',
            'Sepatu',
            'Kulit Samak',
            'Furniture dari kayu',
            'Triplek',
            'Kertas Karton',
            'Kertas Pembungkus',
            'Jamu',
            'Tas anyaman plastik',
            'Kantong Plastik',
            'List Plavon',
            'Batako',
            'Pagar Besi',
            'Barang bangunan dari logam',
            'Mesin Pencacah makanan hewan',
            'Mesin selep kopi/kelapa',
            'Gerobak',
            'Sofa',
            'furnitur dari alumunium',
            'Gitar',
            'Odong-odong',
            'Listrik',
            'Es Tube',
            'Air tersalurkan',
            'Plastik Cacah',
            'Jumlah Proyek',
            'Jumlah IMB yang Diterbitkan',
            'Perdagangan Mobil',
            'Perdagangan Motor rd 2 & 3',
            'Retail',
            'Angkutan Penumpang',
            'Angkutan Bus',
            'Angkutan Barang',
            'Penyeberangan Penumpang',
            'Jasa Pengiriman',
            'Hotel Bukit Daun',
            'Kos Fadelan',
            'Restoran',
            'Agen Pulsa & Paket Data',
            'Iklan',
            'Penyaluran Kredit',
            'Asuransi',
            'Pembiayaan',
            'Jasa Penukaran Uang',
            'OOD',
            'Perumahan',
            'Rental Mobil',
            'Jasa Foto',
            'Gaji Pegawai',
            'Gaji Pegawai Diknas',
            'SMA',
            'Gaji Pegawai Diknes',
            'Klinik',
            'Tiket Masuk',
            'Pakaian Tercuci',
        ];

        foreach ($data as $indikator) {
            Indicator::create(['indikator' => $indikator]);
        }
    }
}
